USE jxsk
GO
CREATE TABLE TEST_S
(
    SNO CHAR(2) NOT NULL,
    SN  CHAR(8) NOT NULL,
    SEX CHAR(2) NULL
        CONSTRAINT DEFAULT_SEX DEFAULT 'ÄÐ'
        CONSTRAINT CHECK_SEX CHECK (SEX = 'ÄÐ' OR SEX = 'Å®'),
    AGE TINYINT NULL
        CONSTRAINT DEFAULT_AGE DEFAULT 18,
    CONSTRAINT CHECK_S_AGE CHECK (AGE >= 14 AND AGE <= 40)
)
GO