USE jiaoxuedb
GO
ALTER TABLE Student
    WITH CHECK ADD CONSTRAINT CHECK_S_AGE CHECK (AGE > 0 AND AGE < 100)
ALTER TABLE Teacher
    WITH CHECK ADD CONSTRAINT CHECK_T_AGE CHECK (AGE > 0 AND AGE < 100)
GO