USE jiaoxuedb
ALTER TABLE SC
    WITH NOCHECK ADD CONSTRAINT FK_S_SC FOREIGN KEY (Sno) REFERENCES Student (Sno) ON DELETE CASCADE
ALTER TABLE SC
    WITH NOCHECK ADD CONSTRAINT FK_C_SC FOREIGN KEY (Cno) REFERENCES Course (Cno) ON DELETE CASCADE
ALTER TABLE TC
    WITH NOCHECK ADD CONSTRAINT FK_T_TC FOREIGN KEY (Tno) REFERENCES Teacher (Tno) ON DELETE CASCADE
ALTER TABLE TC
    WITH NOCHECK ADD CONSTRAINT FK_C_TC FOREIGN KEY (Cno) REFERENCES Course (Cno) ON DELETE CASCADE
GO