USE jiaoxuedb
GO
ALTER TABLE Student
    ADD CONSTRAINT PK_SNO PRIMARY KEY (Sno)
ALTER TABLE Teacher
    ADD CONSTRAINT PK_TNO PRIMARY KEY (Tno)
ALTER TABLE Course
    ADD CONSTRAINT PK_CNO PRIMARY KEY (Cno)
ALTER TABLE Student
    ADD CONSTRAINT UNIQUE_S UNIQUE (Sno)
ALTER TABLE Teacher
    ADD CONSTRAINT UNIQUE_T UNIQUE (Tno)
ALTER TABLE Course
    ADD CONSTRAINT UNIQUE_C UNIQUE (Cno)
GO