USE jiaoxuedb
GO
ALTER TABLE Teacher
    WITH CHECK ADD CONSTRAINT CHECK_T_SEX CHECK (Sex = 'ÄÐ' OR Sex = 'Å®')
ALTER TABLE Teacher
    ADD CONSTRAINT DF_T_SEX DEFAULT 'ÄÐ' FOR Sex
ALTER TABLE Student
    WITH CHECK ADD CONSTRAINT CHECK_S_SEX CHECK (Sex = 'ÄÐ' OR Sex = 'Å®')
ALTER TABLE Student
    ADD CONSTRAINT DF_S_SEX DEFAULT 'ÄÐ' FOR Sex
GO