CREATE TRIGGER TRIGGER_S
    ON S
    FOR UPDATE AS IF UPDATE(SNO)
    BEGIN
        DECLARE @SNO_NEW char(2),@SNO_OLD char(2)
        SELECT @SNO_NEW = SNO FROM Inserted
        SELECT @SNO_OLD = SNO FROM Deleted
        UPDATE SC SET SNO=@SNO_NEW WHERE SNO = @SNO_OLD
    END